# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Users
User.create!(username: 'ChrisChris', first_name: 'Chris', last_name: 'Chris', password: 'password', password_confirmation: 'password' )
User.create!(username: 'TomTom', first_name: 'Tom', last_name: 'Tom', password: 'password', password_confirmation: 'password' )
User.create!(username: 'ZaraZara', first_name: 'Zara', last_name: 'Zara', password: 'password', password_confirmation: 'password' )
User.create!(username: 'FrankyFranky', first_name: 'Franky', last_name: 'Franky', password: 'password', password_confirmation: 'password' )
User.create!(username: 'JoeJoe', first_name: 'Joe', last_name: 'Joe', password: 'password', password_confirmation: 'password' )

# Following
Follow.create!(follower_id: User.find_by_first_name('Chris').id, following_id: User.find_by_first_name('Tom').id)
Follow.create!(follower_id: User.find_by_first_name('Chris').id, following_id: User.find_by_first_name('Zara').id)
Follow.create!(follower_id: User.find_by_first_name('Chris').id, following_id: User.find_by_first_name('Franky').id)
Follow.create!(follower_id: User.find_by_first_name('Chris').id, following_id: User.find_by_first_name('Joe').id)
Follow.create!(follower_id: User.find_by_first_name('Tom').id, following_id: User.find_by_first_name('Chris').id)
Follow.create!(follower_id: User.find_by_first_name('Tom').id, following_id: User.find_by_first_name('Zara').id)
Follow.create!(follower_id: User.find_by_first_name('Tom').id, following_id: User.find_by_first_name('Franky').id)
Follow.create!(follower_id: User.find_by_first_name('Tom').id, following_id: User.find_by_first_name('Joe').id)
Follow.create!(follower_id: User.find_by_first_name('Zara').id, following_id: User.find_by_first_name('Chris').id)
Follow.create!(follower_id: User.find_by_first_name('Zara').id, following_id: User.find_by_first_name('Tom').id)
Follow.create!(follower_id: User.find_by_first_name('Zara').id, following_id: User.find_by_first_name('Franky').id)
Follow.create!(follower_id: User.find_by_first_name('Zara').id, following_id: User.find_by_first_name('Joe').id)
Follow.create!(follower_id: User.find_by_first_name('Franky').id, following_id: User.find_by_first_name('Chris').id)
Follow.create!(follower_id: User.find_by_first_name('Franky').id, following_id: User.find_by_first_name('Tom').id)
Follow.create!(follower_id: User.find_by_first_name('Franky').id, following_id: User.find_by_first_name('Zara').id)
Follow.create!(follower_id: User.find_by_first_name('Franky').id, following_id: User.find_by_first_name('Joe').id)
Follow.create!(follower_id: User.find_by_first_name('Joe').id, following_id: User.find_by_first_name('Chris').id)
Follow.create!(follower_id: User.find_by_first_name('Joe').id, following_id: User.find_by_first_name('Tom').id)
Follow.create!(follower_id: User.find_by_first_name('Joe').id, following_id: User.find_by_first_name('Zara').id)
Follow.create!(follower_id: User.find_by_first_name('Joe').id, following_id: User.find_by_first_name('Franky').id)

# Images
User.find_by_first_name('Chris').images.create!(url: 'http://d5qsyj6vaeh11.cloudfront.net/images/homepage/backgrounds/mayo-rainbow_bg.jpg', lat: '53.2734', long: '9.0489', caption: "When I lost my job, I realized you don/'t need a pot of gold at the end of the rainbow.")
User.find_by_first_name('Chris').images.create!(url: 'http://images.nationalgeographic.com/wpf/media-live/photos/000/067/cache/pastoral-landscape_6792_600x450.jpg', lat: '53.3428', long: '6.2661', caption: "When I stood in my ancestor/'s backyard, I realized how deep roots grow.")
User.find_by_first_name('Chris').images.create!(url: 'http://backroads_web.s3.amazonaws.com/images/trips/2013/slideshowsnew/BIRQ-ireland-biking-7.jpg', lat: '52.6675', long: '8.6261', caption: "When I stepped outside my comfort zone, I realized the grass is always greener on this side.")
User.find_by_first_name('Chris').images.create!(url: 'http://www.hillwalkireland.com/slider/5_Ireland_Hiking_Trips_West_of_Ireland_Walking_Tours.jpg', lat: '52.7106', long: '8.8784', caption: "When I left the city, I realized peace is precious.")
User.find_by_first_name('Chris').images.create!(url: 'http://www.brideswithoutborders.com/wp/wp-content/uploads/2011/11/ireland.jpg', lat: '52.0599', long: '9.5072', caption: "When I was alone, I realized how transient life is.")
User.find_by_first_name('Tom').images.create!(url: 'http://d5qsyj6vaeh11.cloudfront.net/images/homepage/backgrounds/mayo-rainbow_bg.jpg', lat: '56.2734', long: '9.0489', caption: "When I lost my job, I realized you don/'t need a pot of gold at the end of the rainbow.")
User.find_by_first_name('Tom').images.create!(url: 'http://images.nationalgeographic.com/wpf/media-live/photos/000/067/cache/pastoral-landscape_6792_600x450.jpg', lat: '58.3428', long: '6.2661', caption: "When I stood in my ancestor/'s backyard, I realized how deep roots grow.")
User.find_by_first_name('Tom').images.create!(url: 'http://backroads_web.s3.amazonaws.com/images/trips/2013/slideshowsnew/BIRQ-ireland-biking-7.jpg', lat: '60.6675', long: '8.6261', caption: "When I stepped outside my comfort zone, I realized the grass is always greener on this side.")
User.find_by_first_name('Tom').images.create!(url: 'http://www.hillwalkireland.com/slider/5_Ireland_Hiking_Trips_West_of_Ireland_Walking_Tours.jpg', lat: '64.7106', long: '8.8784', caption: "When I left the city, I realized peace is precious.")
User.find_by_first_name('Tom').images.create!(url: 'http://www.brideswithoutborders.com/wp/wp-content/uploads/2011/11/ireland.jpg', lat: '66.0599', long: '9.5072', caption: "When I was alone, I realized how transient life is.")
User.find_by_first_name('Zara').images.create!(url: 'http://d5qsyj6vaeh11.cloudfront.net/images/homepage/backgrounds/mayo-rainbow_bg.jpg', lat: '68.2734', long: '9.0489', caption: "When I lost my job, I realized you don/'t need a pot of gold at the end of the rainbow.")
User.find_by_first_name('Zara').images.create!(url: 'http://images.nationalgeographic.com/wpf/media-live/photos/000/067/cache/pastoral-landscape_6792_600x450.jpg', lat: '70.3428', long: '6.2661', caption: "When I stood in my ancestor/'s backyard, I realized how deep roots grow.")
User.find_by_first_name('Zara').images.create!(url: 'http://backroads_web.s3.amazonaws.com/images/trips/2013/slideshowsnew/BIRQ-ireland-biking-7.jpg', lat: '74.6675', long: '8.6261', caption: "When I stepped outside my comfort zone, I realized the grass is always greener on this side.")
User.find_by_first_name('Zara').images.create!(url: 'http://www.hillwalkireland.com/slider/5_Ireland_Hiking_Trips_West_of_Ireland_Walking_Tours.jpg', lat: '76.7106', long: '8.8784', caption: "When I left the city, I realized peace is precious.")
User.find_by_first_name('Zara').images.create!(url: 'http://www.brideswithoutborders.com/wp/wp-content/uploads/2011/11/ireland.jpg', lat: '78.0599', long: '9.5072', caption: "When I was alone, I realized how transient life is.")
User.find_by_first_name('Franky').images.create!(url: 'http://d5qsyj6vaeh11.cloudfront.net/images/homepage/backgrounds/mayo-rainbow_bg.jpg', lat: '80.2734', long: '9.0489', caption: "When I lost my job, I realized you don/'t need a pot of gold at the end of the rainbow.")
User.find_by_first_name('Franky').images.create!(url: 'http://images.nationalgeographic.com/wpf/media-live/photos/000/067/cache/pastoral-landscape_6792_600x450.jpg', lat: '82.3428', long: '6.2661', caption: "When I stood in my ancestor/'s backyard, I realized how deep roots grow.")
User.find_by_first_name('Franky').images.create!(url: 'http://backroads_web.s3.amazonaws.com/images/trips/2013/slideshowsnew/BIRQ-ireland-biking-7.jpg', lat: '84.6675', long: '8.6261', caption: "When I stepped outside my comfort zone, I realized the grass is always greener on this side.")
User.find_by_first_name('Franky').images.create!(url: 'http://www.hillwalkireland.com/slider/5_Ireland_Hiking_Trips_West_of_Ireland_Walking_Tours.jpg', lat: '86.7106', long: '8.8784', caption: "When I left the city, I realized peace is precious.")
User.find_by_first_name('Franky').images.create!(url: 'http://www.brideswithoutborders.com/wp/wp-content/uploads/2011/11/ireland.jpg', lat: '88.0599', long: '9.5072', caption: "When I was alone, I realized how transient life is.")
User.find_by_first_name('Joe').images.create!(url: 'http://d5qsyj6vaeh11.cloudfront.net/images/homepage/backgrounds/mayo-rainbow_bg.jpg', lat: '90.2734', long: '9.0489', caption: "When I lost my job, I realized you don/'t need a pot of gold at the end of the rainbow.")
User.find_by_first_name('Joe').images.create!(url: 'http://images.nationalgeographic.com/wpf/media-live/photos/000/067/cache/pastoral-landscape_6792_600x450.jpg', lat: '92.3428', long: '6.2661', caption: "When I stood in my ancestor/'s backyard, I realized how deep roots grow.")
User.find_by_first_name('Joe').images.create!(url: 'http://backroads_web.s3.amazonaws.com/images/trips/2013/slideshowsnew/BIRQ-ireland-biking-7.jpg', lat: '94.6675', long: '8.6261', caption: "When I stepped outside my comfort zone, I realized the grass is always greener on this side.")
User.find_by_first_name('Joe').images.create!(url: 'http://www.hillwalkireland.com/slider/5_Ireland_Hiking_Trips_West_of_Ireland_Walking_Tours.jpg', lat: '96.7106', long: '8.8784', caption: "When I left the city, I realized peace is precious.")
User.find_by_first_name('Joe').images.create!(url: 'http://www.brideswithoutborders.com/wp/wp-content/uploads/2011/11/ireland.jpg', lat: '98.0599', long: '9.5072', caption: "When I was alone, I realized how transient life is.")
